name: Metrics

on:
  schedule: [{cron: "0 5 */1 * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.README_TOKEN }}

          #options
          user: thespad
          template: classic
          base: header, activity, community, repositories, metadata
          config_octicon: yes
          config_timezone: Europe/London
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_visibility: all
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_rss: yes
          plugin_rss_limit: 5
          plugin_rss_source: https://www.spad.uk/posts/index.xml
          plugin_stars: yes
          plugin_stars_limit: 4
